# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-04-28 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryvideo',
            name='property',
        ),
        migrations.RemoveField(
            model_name='entryinteface',
            name='entry_video',
        ),
        migrations.AddField(
            model_name='entryinteface',
            name='isClimbing',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='EntryVideo',
        ),
    ]
