# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-04-28 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_auto_20200428_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='entry.Entry')),
            ],
        ),
    ]
