# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-04-28 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_entryvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutusimage',
            name='property',
        ),
        migrations.RemoveField(
            model_name='entryinteface',
            name='isClimbing',
        ),
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='AboutUsImage',
        ),
    ]
