# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-04-28 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_auto_20200428_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryinteface',
            name='isClimbing',
            field=models.BooleanField(default=False),
        ),
    ]
