# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-04-29 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0005_entryinteface_isclimbing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryinteface',
            name='isClimbing',
        ),
    ]
