# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-05-01 14:16
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0006_remove_entryinteface_isclimbing'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryinteface',
            name='entry_video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='entryimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='entryinteface',
            name='title_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='title_image'),
        ),
    ]
