# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-04-28 16:24
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_auto_20200428_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('leon_image', models.ImageField(null=True, upload_to='aboutus/authors/leon')),
                ('magda_image', models.ImageField(null=True, upload_to='aboutus/authors/magda')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='AboutUsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='aboutus/authors')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abus_images', to='main.AboutUs')),
            ],
        ),
    ]
